name = "ParticleDA"
uuid = "61cd1fb4-f4c4-4bc8-80c6-ea5639a6ca2e"
authors = ["Mos√® Giordano and Tuomas Koskela"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FieldMetadata = "bf96fef3-21d2-5d20-8afa-0e7d4c32a885"
Future = "9fa8497b-333b-5362-9e8d-4d0656e87820"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
Distributions = "0.22, 0.23, 0.24, 0.25"
EllipsisNotation = "1.1.0"
FFTW = "1"
FieldMetadata = "0.3.1"
HDF5 = "0.14, 0.15, 0.16"
MPI = "0.19"
TimerOutputs = "0.5"
YAML = "0.4"
julia = "1.5"
