name = "ParticleDA"
uuid = "61cd1fb4-f4c4-4bc8-80c6-ea5639a6ca2e"
authors = ["Mos√® Giordano and Tuomas Koskela and Dan Giles and Matt Graham"]
version = "0.1.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
HDF5 = "0.14, 0.15, 0.16"
MPI = "0.19"
TimerOutputs = "0.5"
YAML = "0.4"
julia = "1.7"
