name = "ParticleDA"
uuid = "61cd1fb4-f4c4-4bc8-80c6-ea5639a6ca2e"
authors = ["Mos√® Giordano and Tuomas Koskela and Dan Giles and Matt Graham"]
version = "1.2.0"

[deps]
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
OpenMPI_jll = "fe0851c0-eecd-5654-98d4-656369965a5c"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
ChunkSplitters = "3.1"
HDF5 = "0.14, 0.15, 0.16, 0.17"
LinearAlgebra = "<0.0.1, 1"
MPI = "0.20.22"
OpenMPI_jll = "4"
PDMats = "0.11.17"
Random = "<0.0.1, 1"
Statistics = "<0.0.1, 1"
StructArrays = "0.6.15, 0.7"
TimerOutputs = "0.5"
YAML = "0.4"
julia = "1.7"
