[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulRecipes = "42071c24-d89e-48dd-8a24-8a12d9b8861f"

[compat]
HDF5 = "0.15"
Plots = "1.14"
Unitful = "1.7"
UnitfulRecipes = "1.2"
julia = "1.5"
